export const serviceData = [
  {
    id: 1,
    title: "Day at Dino Beach",
    longTitle: "Single-Page Website",
    price: 200,
    description:
      "Everything your customers need to know about your business on a single page, right away!",
    details: [
      // "Includes",
      "Contact Forms & Interactions",
      "Social media packet",
      "SEO Strategy",
      "Perfect for: one-page portfolios",
    ],
  },
  {
    id: 2,
    title: "Weekend Getaway",
    longTitle: "Multi-Page Website",
    price: 300,
    description: "You want your customers to know what you do, and a way to get your product to them",
    details: [
      // "Details 2",
      "Contact Forms & Interactions",
      "Social media packet",
      "SEO Strategy",
      "Perfect for: restaurants, single-product stores",
    ],
  },
  {
    id: 3,
    title: "Influenshell",
    longTitle: "Blogging Platform",
    price: 400,
    description: "You're ready to influence your viewers with your fashion, food, DIY or just about anything",
    details: [
      // "Details 3",
      "Contact Forms & Interactions",
      "Social media packet",
      "SEO Strategy",
      "Perfect for: bloggers",
    ],
  },
  {
    id: 4,
    title: "Dinoland",
    longTitle: "E-commerce Business",
    price: 500,
    description: "We'll build out a full e-commerce business and bring you money ASAP",
    details: [
      // "Details 4",
      "Contact Forms & Interactions",
      "Social media packet",
      "Shopify Set Up",
      "Perfect for: e-commerce store",
    ],
  },
  {
    id: 5,
    title: "Build a Beach",
    price: 600,
    description: "Some text describing it goes here",
    details: [
      // "Details 5",
      "Contact Forms & Interactions",
      "Social media packet",
      "SEO Strategy",
      "Perfect for: E-commerce a",
    ],
  },
];
